/**
 * PID Controller - C Header
 * Auto-generated by Control Systems Playground
 *
 * Parameters:
 *   Kp = 1
 *   Ki = 0.5
 *   Kd = 0.1
 */

#ifndef CPID_H
#define CPID_H

/** Persistent state passed into every cyclic call */
typedef struct {
    double integral;
    double prev_error;
    double output;
} PIDState;

/**
 * PID cyclic function – call once per control cycle.
 *
 * @param kp          Proportional gain
 * @param ki          Integral gain
 * @param kd          Derivative gain
 * @param input       Desired value
 * @param state       Pointer to persistent state (updated in place)
 * @param dt          Time step in seconds
 * @return            Controller output
 */
double pid_cyclic(double kp, double ki, double kd, double input,
                  PIDState* state, double dt);

#endif /* CPID_H */
